version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    volumes:
    - ./db:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      -8081:8081
    depends_on:
      - mongo


  web:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    depends_on:
      - mongo
    ports:
      - 8080:8080
